### ISSUE TITLE
Crashing when changing profiles

### ISSUE THREAD

**Issue by ZombieErebus** [Slivo-fr/elinor-reloaded#11]
I have 2 profiles for market trading, one for selling at the current station with buy orders within 1 jump and one for updating sell orders at 1 jump range with buy orders within 1 jump. 

If I "export to file", click market logs to delete logs then attempt to switch profile the app freezes and must be force-closed through task manager. 

Not that big of a deal, I just close the app before changing profiles but thought I would file a report anyway

**Comment by Slivo-fr** [comment]
That's a bit strange. I'll try to reproduce it !

**Comment by Slivo-fr** [comment]
I've been able to reproduce and fix this issue, it will be included in the next beta release (1.9.0-beta2)
