### ISSUE TITLE
Please correct the price change formula/

### ISSUE THREAD

**Issue by makstronchik** [Slivo-fr/elinor-reloaded#15]
Please correct the price change formula. Here's how it works now "Change: Order prices can only be specified with a maximum precision of 4 significant figures.

Currently in EVE, all order prices can be specified to a 0.01 ISK precision, regardless of the magnitude. This will be changing and will use discrete ticks to a precision of four significant figures.

As an example, the following list shows the only acceptable ticks around the 1 million ISK region. All prices must be exactly set to one of these tick levels, and intermediate values will be rounded up/down to the next tick.

1,112,000
1,111,000
1,110,000
1,109,000
...
1,002,000
1,001,000
1,000,000
999,900
999,800
999,700"

**Comment by Slivo-fr** [comment]
Hey there, I'm going to try releasing an update for this.

**Comment by Slivo-fr** [comment]
Please checkout https://github.com/Slivo-fr/elinor-reloaded/releases/tag/v1.9.0-beta1

**Comment by makstronchik** [comment]
Thank you very much Slivo-fr, now everything is working correctly,the eve community thanks you for your efforts.

**Comment by Slivo-fr** [comment]
You're welcome, make sure you get the stable update once it's released, the app won't notify you about it
