### ISSUE TITLE
Market fees have been changed

### ISSUE THREAD

**Issue by ndite** [Slivo-fr/elinor-reloaded#18]
Broker fee has been reduced and sales fee has been increased.

Market:
The three month planned tax relief period has concluded, with new market tax changes being applied after review:

Sales Tax: 8%
Brokers Fee: 3%
Base Unmodified Taxes:

Sales Tax: 2.5% -> 8.0% (Previously 5.0%)
Brokers Fee: 2.5% -> 3.0% (Previously 5.0%)
Total Taxes: 5.0% -> 11.0% (Previously 10.0%)
Minimum Taxes (Modified by Skills, Standings, etc):

Sales Tax: 1.125% -> 3.6% (Previously 2.25%)
Brokers Fee: 0.5% -> 1.0% (Previously 3.0%)
Total Taxes: 1.625% -> 4.6% (Previously 5.25%)

**Comment by Slivo-fr** [comment]
Thanks for letting me know, and thanks a lot for the pull request !
I will do some testing over the next days.

When will those change go live on TQ ?

**Comment by ndite** [comment]
thanks for quick reply. they are live for a few days now.
I just got back after a few years and tried to find this app.. forgot it's name but eventually got it here.

also there is a difference whether the user is omega or not but i guess that's not important atm.

**Comment by Slivo-fr** [comment]
Welcome back then ! 
I'll try to release soon to match the TQ update

I'll keep this alpha thing in mind, I could add a checkbox somewhere ...

Thanks again for contributing :)

**Comment by Slivo-fr** [comment]
Released !
