### ISSUE TITLE
Incorrect predefined API link

### ISSUE THREAD

**Issue by Venique** [Slivo-fr/elinor-reloaded#4]
If you press 'Create new API key' while creating new character through 'Import from eve API', you will be redirected to:
`https://support.eveonline.com/api/Key/CreatePredefined/524296/0/false`
which is 404 because correct link would be:
`https://community.eveonline.com/support/api-key/CreatePredefined?accessMask=524296`

**Comment by Slivo-fr** [comment]
Thanks, I will update this !
