### ISSUE TITLE
Advanced increment settings

### ISSUE THREAD

**Issue by Venique** [Slivo-fr/elinor-reloaded#5]
How it works? I can't get how to increment lowest sell order / highest buy order on specific value. For example, on 1ISK.

I export market logs, Elinor see that lowest sell order is 1 000 000 ISK but it doesn't ajust it to 1 000 001 ISK and it doesn't matter which settings I set in advanced increment.

**Comment by Slivo-fr** [comment]
Increment settings was an unfinished feature of last dev, I believe you have to fill all the 4 field to get it working.

**Comment by relh** [comment]
The way to make advanced increment work is to set sell price fraction to 0.1 and threshold to really large. Then it will just always use sell price fraction/buy price fraction. Please disregard this PR I was trying to put in numbers like 99 mistakenly

**Comment by Slivo-fr** [comment]
Advanced increment settings will be gone in 1.9.0
