### ISSUE TITLE
Add a profit w/ average moving volume

### ISSUE THREAD

**Issue by insipx** [Slivo-fr/elinor-reloaded#8]
Would be nice to see not only the profit from one item, but automatically calculate the profit based upon the average moving volume of the last 30 days.

**Comment by Slivo-fr** [comment]
Hello InsidiousMind
I'm actually not gathering volume data and not doing any calculation on this subject.

Even if a reliable information of this kind would be helpful, I don't think this would really be the case.
Plus, I'm not trading anymore for the moment, and if I will keep Elinor running and up to date, I won't add new features.

However, as this project is open source, feel free to fork/contribute if you like !

**Comment by InsidiousMind** [comment]
Hey @Slivo-fr 

IMO the profit of one item is helpful, but it can sometimes be deceiving. IE, maybe you find an item with a margin of 5mil, great! But then i find myself having to go through into the market data for this item anyway, to check on the volume and see if it's really worth getting. Sometimes, the volume is shit ~ (think, 1 item every other day) other times it's OK. The reverse can also happen.

Usually, I buy 10% of an items volume for a safe investment, and if i'm speculating/living life on the edge i'll buy various percentages.

However, i totally understand. Unfortunately I don't really regard C# as my forte, nor have I ever touched it. I'm sure this was a good design decision by you (or whoever created Elinor first), but I'm simply not apt to learn everything I need to know.

Maybe, in the future, I will find myself learning C# and contribute.

Anyways, cheers!
